"""Initial schema

Revision ID: 86b43eefbfe5
Revises: 
Create Date: 2026-04-09 20:16:09.430402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b43eefbfe5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email_domain', sa.String(length=255), nullable=True),
    sa.Column('ceo', sa.String(length=128), nullable=True),
    sa.Column('address_hq', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('transit_map_link', sa.String(length=256), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('gtfs_feed_url', sa.String(length=512), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_transit_system_name')
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('short_description', sa.String(length=200), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functional_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('standard_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('vendor_email', sa.String(length=255), nullable=True),
    sa.Column('vendor_phone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_vendor_name')
    )
    op.create_table('component_integration',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'integration_point_id')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('criticality', sa.Enum('high', 'medium', 'low', name='criticality'), nullable=False),
    sa.Column('functional_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['functional_area_id'], ['functional_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_standard',
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('integration_point_id', 'standard_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('parent_product_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_stage', sa.Enum('planned', 'pilot', 'production', 'deprecated', 'retired', name='lifecyclestage'), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_parent_product_id'), ['parent_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('tag_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_group_id'], ['tag_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('change_summary', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'sub', name='uq_user_provider_sub')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_provider_sub', ['provider', 'sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('component_tag',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'tag_id')
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('implementation_notes', sa.String(length=1000), nullable=True),
    sa.Column('security_review_date', sa.Date(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'function_id', 'component_id', name='uq_configuration_agency_function_component')
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index('ix_configuration_agency_function', ['agency_id', 'function_id'], unique=False)
        batch_op.create_index('ix_configuration_component', ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_function_id'), ['function_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_status'), ['status'], unique=False)

    op.create_table('function_component',
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('function_id', 'component_id')
    )
    op.create_table('integration_tag',
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('integration_point_id', 'tag_id')
    )
    op.create_table('product_integration',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'integration_point_id')
    )
    op.create_table('product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('support_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_product_version')
    )
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.create_index('ix_product_version_product_id_version', ['product_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_versions_product_id'), ['product_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('suggested_value', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index('ix_suggestion_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_suggestion_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)

    op.create_table('verified_agency_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verified_agency_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verified_agency_domains_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verified_agency_domains_domain'), ['domain'], unique=True)

    op.create_table('configuration_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuration_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_history_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_history_timestamp'), ['timestamp'], unique=False)

    op.create_table('configuration_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_id', 'product_id', name='uq_configuration_product')
    )
    with op.batch_alter_table('configuration_products', schema=None) as batch_op:
        batch_op.create_index('ix_configuration_product_product_version', ['product_id', 'product_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_product_version_id'), ['product_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_status'), ['status'], unique=False)

    op.create_table('configuration_service_type',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('configuration_id', 'service_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_service_type')
    with op.batch_alter_table('configuration_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_products_status'))
        batch_op.drop_index(batch_op.f('ix_configuration_products_product_version_id'))
        batch_op.drop_index(batch_op.f('ix_configuration_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_configuration_products_configuration_id'))
        batch_op.drop_index('ix_configuration_product_product_version')

    op.drop_table('configuration_products')
    with op.batch_alter_table('configuration_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_configuration_history_configuration_id'))

    op.drop_table('configuration_history')
    with op.batch_alter_table('verified_agency_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verified_agency_domains_domain'))
        batch_op.drop_index(batch_op.f('ix_verified_agency_domains_agency_id'))

    op.drop_table('verified_agency_domains')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_entity_type'))
        batch_op.drop_index(batch_op.f('ix_suggestions_entity_id'))
        batch_op.drop_index('ix_suggestion_status_created')
        batch_op.drop_index('ix_suggestion_entity')

    op.drop_table('suggestions')
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_versions_product_id'))
        batch_op.drop_index('ix_product_version_product_id_version')

    op.drop_table('product_versions')
    op.drop_table('product_integration')
    op.drop_table('integration_tag')
    op.drop_table('function_component')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_status'))
        batch_op.drop_index(batch_op.f('ix_configurations_function_id'))
        batch_op.drop_index(batch_op.f('ix_configurations_component_id'))
        batch_op.drop_index(batch_op.f('ix_configurations_agency_id'))
        batch_op.drop_index('ix_configuration_component')
        batch_op.drop_index('ix_configuration_agency_function')

    op.drop_table('configurations')
    op.drop_table('component_tag')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_agency_id'))
        batch_op.drop_index('ix_user_provider_sub')

    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('update_logs')
    op.drop_table('tags')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_products_parent_product_id'))

    op.drop_table('products')
    op.drop_table('integration_standard')
    op.drop_table('functions')
    op.drop_table('component_integration')
    op.drop_table('vendors')
    op.drop_table('tag_groups')
    op.drop_table('standards')
    op.drop_table('service_types')
    op.drop_table('integration_points')
    op.drop_table('functional_areas')
    op.drop_table('components')
    op.drop_table('agencies')
    # ### end Alembic commands ###
